# Nome do Workflow
name: Deploy to GitHub Pages

# Gatilho: Executa sempre que houver um push na branch 'main'
on:
  push:
    branches: [ "main" ]

# Permissões necessárias para que a Action possa fazer o deploy para o GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Define as tarefas a serem executadas
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Define o ambiente de deploy para o GitHub Pages, necessário para o deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Define a sequência de passos do job
    steps:
      # 1. Baixa o código do repositório para a máquina virtual
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Encontra e substitui os placeholders pelas chaves secretas do Firebase
      - name: Replace Firebase Config Placeholders
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: |
          sed -i "s|%%FIREBASE_API_KEY%%|$FIREBASE_API_KEY|g" index.html
          sed -i "s|%%FIREBASE_AUTH_DOMAIN%%|$FIREBASE_AUTH_DOMAIN|g" index.html
          sed -i "s|%%FIREBASE_PROJECT_ID%%|$FIREBASE_PROJECT_ID|g" index.html
          sed -i "s|%%FIREBASE_STORAGE_BUCKET%%|$FIREBASE_STORAGE_BUCKET|g" index.html
          sed -i "s|%%FIREBASE_MESSAGING_SENDER_ID%%|$FIREBASE_MESSAGING_SENDER_ID|g" index.html
          sed -i "s|%%FIREBASE_APP_ID%%|$FIREBASE_APP_ID|g" index.html

      # 3. Configura o ambiente para o GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 4. Cria o artefato (a pasta com o site final) e faz o upload
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Publica a partir da raiz do projeto, já que o index.html está lá
          path: '.'

      # 5. Faz o deploy final para o GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
